language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

before_install:

script:
  - composer install
  - composer test
  
matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - hhvm